# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev2_test',
                'doc_host': 'https://spinbris.github.io',
                'git_url': 'https://github.com/spinbris/nbdev2_test',
                'lib_path': 'nbdev2_test'},
  'syms': {'nbdev2_test.core': {'nbdev2_test.core.foo': ('core.html#foo', 'nbdev2_test/core.py')}}}